require_relative "./tic_tac_toe/board.rb"
require_relative "./tic_tac_toe/computer_logic.rb"
require_relative "./tic_tac_toe/console_output.rb"
require_relative "./tic_tac_toe/game.rb"
require_relative "./tic_tac_toe/players.rb"
require_relative "./tic_tac_toe/winner_logic.rb"
